### ISSUE TITLE
with latest version more info is being shown as well as popup card...nothing else changed

### ISSUE THREAD

**Issue by jouster1974** [thomasloven/hass-browser_mod#413]
installed Browser mode latest changes today and now popup cards setup yesterday also show the more-info dialog box when they didn't before.

have also installed 2022.9 so this could be a combo issue but thought I would mention it just in case but it was working fine on prior release of Core

**Comment by tigers75** [comment]
I have the same problem, definitely happened after upgrading to 2022.9. The standard more info and the pop up both show up, and I have to close the standard one before operating with the pop up

**Comment by CelestinoMarini** [comment]
I have the same problem about pop up...not showed

**Comment by tigers75** [comment]
> I have the same problem about pop up...not showed

If it's not showing then it's not the same problem: for me the pop up shows up both together with the standard more info window

**Comment by neutrondev20** [comment]
some problem

**Comment by tigers75** [comment]
> 

Can confirm that reverting back to 2022.8 solved the problem, that showed up also on PC (maybe I didn't refresh the cache correctly - I did a CTRL+F5 refresh but still...). Hope it's fixable, I just discovered the pop-ups and was starting to adopt them.

**Comment by holdestmade** [comment]
Same problem here after updating to 2022.9

**Comment by tigers75** [comment]
If I understand correctly you have a pop-up card activated by a browser event, while I'm experiencing the problem on a pop-up card defined "as a card" with the new 2.0, maybe that's the difference?

**Comment by tigers75** [comment]
I agree: the vanilla more-info pop has significantly changed in this version.

**Comment by holdestmade** [comment]
> What browser mod versions is everything using with this issue?
> 
> Anyone using browser mod 2?

Yes, v2

**Comment by holdestmade** [comment]
So I have a popups.yaml file, this is the 1st part of it with 3 popups:

```
type: vertical-stack
cards:
  - type: custom:popup-card
    entity: alarm_control_panel.home
    title: Alarm
    card:
      type: vertical-stack
      cards:
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              entity: binary_sensor.alarm_sensors_armed_away
              show_name: false
              show_entity_picture: true
              entity_picture: /local/images/icons8-home-alarm-armed-day-clear.png
              size: 30%
              tap_action:
                action: more-info
              state:
                - value: "on"
                  entity_picture: /local/images/icons8-home-alarm-armed-day-active.png
            - type: "custom:button-card"
              entity: binary_sensor.alarm_sensors_armed_night
              show_name: false
              show_entity_picture: true
              entity_picture: /local/images/icons8-home-alarm-armed-night-clear.png
              size: 30%
              tap_action:
                action: more-info
              state:
                - value: "on"
                  entity_picture: /local/images/icons8-home-alarm-armed-night-active.png
        - type: alarm-panel
          entity: alarm_control_panel.home
          states:
            - arm_away
            - arm_night

  - type: custom:popup-card
    entity: switch.filament_dryer
    title: Filament Dryer
    card:
      type: vertical-stack
      cards:
        - type: entities
          show_header_toggle: false
          entities:
            - entity: switch.filament_dryer
              name: Power
            - entity: input_boolean.filament_dryer_start
              name: Timer Start
              state_color: true
            - entity: input_number.filament_dryer_duration
              name: Timer Duration
            - type: custom:timer-bar-card
              entity: timer.filament_dryer_duration
              name: Timer
              state_color: true
              bar_direction: rtl
              bar_foreground: "#808080"
              bar_background: "var(--mdc-theme-primary, #6200ee)"
              text_width: 4em
            - entity: sensor.filament_dryer_temperature
              name: Temperature
            - entity: sensor.filament_dryer_status
              name: State
            - entity: sensor.filament_dryer_voltage
              name: Electricity
              state_header: Voltage
              type: custom:multiple-entity-row
              entities:
                - entity: sensor.filament_dryer_current
                  name: Current
                - entity: sensor.filament_dryer_power
                  name: Power
            - entity: sensor.filament_dryer_total_daily_energy
              name: Today
              state_header: Energy
              type: custom:multiple-entity-row
              entities:
                - entity: sensor.filament_dryer_total_daily_cost
                  name: Cost

  - type: custom:popup-card
    entity: light.landing_light
    title: Landing Light
    card:
      type: vertical-stack
      cards:
        - type: custom:light-entity-card
          entity: light.landing_light
          persist_features: true
          full_width_sliders: true
          header: Light
        - type: entities
          entities:
            - entity: input_boolean.landing_automations
              name: Automations
```
Then in my dashboard view:

```
views:
  - title: Home
    icon: "mdi:home"
    panel: true
    #path: default_view
    cards:
      - type: vertical-stack
        cards:
          - type: grid
            columns: 4
            square: false
            cards:
              - type: vertical-stack
                cards:
                  - !include dashboard-components/weather.yaml
                  - !include dashboard-components/people.yaml
                  - !include dashboard-components/air_quality.yaml
                  - !include dashboard-components/security.yaml
                  - !include dashboard-components/bins.yaml
                  #- !include dashboard-components/christmas.yaml
                  - !include dashboard-components/alexa_next.yaml
              - type: vertical-stack
                cards:
                  - !include dashboard-components/garden_front.yaml
                  - !include dashboard-components/garden_back.yaml
                  - !include dashboard-components/garage.yaml
                  - !include dashboard-components/workshop.yaml
              - type: vertical-stack
                cards:
                  - !include dashboard-components/living_room.yaml
                  - !include dashboard-components/kitchen.yaml
                  - !include dashboard-components/utility.yaml
                  - !include dashboard-components/toilet.yaml
                  - !include dashboard-components/hall.yaml
                  - !include dashboard-components/landing.yaml
              - type: vertical-stack
                cards:
                  - !include dashboard-components/bedroom.yaml
                  - !include dashboard-components/alices_room.yaml
                  - !include dashboard-components/bens_room.yaml
                  - !include dashboard-components/guest_bedroom.yaml
                  - !include dashboard-components/ensuite.yaml
                  - !include dashboard-components/bathroom.yaml
                  - !include dashboard-components/popups.yaml
          - type: vertical-stack
            cards:
              - !include dashboard-components/cameras.yaml
              - !include dashboard-components/popups.yaml
```

When I click on a an entity, the more-info popup shows at the top and the browser_mod popup shows up in the centre over the more-info. Escape closes both windows

**Comment by holdestmade** [comment]
It doesn't happen on my mobile (android).

**Comment by holdestmade** [comment]
https://drive.google.com/file/d/1rjPi07LK2jo6gCHE4S9GikrPYJbtQrX2/view?usp=sharing

**Comment by tigers75** [comment]
> It doesn't happen on my mobile (android).

It does both on my mobile Android and on iPad (latest iOS). I'm using the official app on both.
Still I don't understand if someone is NOT experiencing this issue: I see no reply after 8 days and it seems quite a big bug to me.

**Comment by holdestmade** [comment]
> He mentioned browser mod always tried to close the more-info pop-up as fast as possible. The more-info pop-up has likely become significantly faster and browser mod may need to be modified to fix it. Could be simple, could be complicated.

Is it maybe because the more-info box is now at the top of the screen ? It might have been there before but under the popup card ? Maybe the browser-mod popup card could be moved to the top as well ?

**Comment by tigers75** [comment]
> > > It doesn't happen on my mobile (android).
> > 
> > 
> > It does both on my mobile Android and on iPad (latest iOS). I'm using the official app on both. Still I don't understand if someone is NOT experiencing this issue: I see no reply after 8 days and it seems quite a big bug to me.
> 
> What browser mod version are you on?
> 
> I talked to Thomas (browser mod developer) a few days ago on discord. He mentioned browser mod always tried to close the more-info pop-up as fast as possible. The more-info pop-up has likely become significantly faster and browser mod may need to be modified to fix it. Could be simple, could be complicated.

I don't know, but if he came here we could help in in debugging the problem, on ourselves we are pretty much playing guess games...

**Comment by tigers75** [comment]
I believe it's in the title: we are talking about latest version of browser_mod (that's 2.1.3 at the moment to be clear, but it was the same with all 2.x releases) properly configured and working fine in HA 2022.8.x but broken in HA 2022.9.x

**Comment by holdestmade** [comment]
> the original more-info pop up is on the background visually but it has focus (this means I can't click anything on the browser_mod popup even if it's on top, but I can click on the contents of the "original" more-info even if it's behind.

Strange, I can click on either the pop up card or the more-info card and the both respond to clicks

**Comment by tigers75** [comment]
This is what happens to me (on PC in a Chrome tab): I can click freely on the original pop-up, the first clic on the browser_mod pop-up closes the original more-info and only the second click has effect on the pop-up card.

![Browser_mod_popup](https://user-images.githubusercontent.com/37505492/190456640-5a67ba70-9381-4b2a-aba5-16c12d48364c.gif)

**Comment by tigers75** [comment]
Just to add some more info I noticed that sometimes it starts to work as intended from the same machine I took the video in my previous message. I'll try to isolate the conditions, I noticed it now as the PC just waked from sleep mode, don't know if that's relevant, will investigate.

**Comment by jouster1974** [comment]
I know I could update again and go back to a backup if needed...but ahs this been rectified in anyway?

**Comment by tigers75** [comment]
Everything is silent, we don't even know if this is being addressed in any way. 
It should be possible to revert to previous version, just do the update process in reverse.

**Comment by jouster1974** [comment]
to answer my own question, no this is not resolved yet.....just tried it on the lastest update, 2022.9.6 (I think) and as soon as I hot for a popup, the more info screen shoes again too....so now rolling back to a restore point.

**Comment by holdestmade** [comment]
Just stumbled on another oddity, if you double click an entity that has a custom pop up card assigned, only the more-info card (with title ".") appears, not the custom pop up card

**Comment by holdestmade** [comment]
Just updated to HA 2022.10.0 and the issue seems to have gone

**Comment by slimpdev** [comment]
> Just updated to HA 2022.10.0 and the issue seems to have gone

Nope, still there for me. 
I use service: browser_mod.more_info

**Comment by holdestmade** [comment]
> > Just updated to HA 2022.10.0 and the issue seems to have gone
> 
> Nope, still there for me. I use service: browser_mod.more_info

I use the more-info replacements in dashboard views and, after a cache clear, all seems to work fine now

**Comment by tigers75** [comment]
First I create a custom pop-up card in the panel, then I select the entity I want it associated with and the type of card that must be displayed with its entities, like this:
Hope this helps.

```
type: custom:popup-card
entity: cover.t_cameram_f_cover_1
dismissable: true
card:
  type: vertical-stack
  cards:
    - type: custom:mushroom-cover-card
      entity: cover.tapparelle_notte
      show_position_control: true
      secondary_info: none
    - type: custom:mushroom-cover-card
      entity: cover.t_cameram_f_cover_1
      show_position_control: true
      layout: horizontal
    - type: custom:mushroom-cover-card
      entity: cover.t_cameram_pf_cover_1
      show_position_control: true
      layout: horizontal
    - type: custom:mushroom-cover-card
      entity: cover.t_pf_camera1_cover_1
      show_position_control: true
      layout: horizontal
    - type: custom:mushroom-cover-card
      entity: cover.t_f_camera2_cover_1
      show_position_control: true
      layout: horizontal
    - type: custom:mushroom-cover-card
      entity: cover.t_pf_camera2_cover_1
      show_position_control: true
      layout: horizontal
    - type: custom:mushroom-cover-card
      entity: cover.t_bagnom_pf_cover_1
      show_position_control: true
      layout: horizontal
title: Tapparelle zona notte
size: normal

```

**Comment by holdestmade** [comment]
> @tigers75 can you post some example with "more-info replacement card"? Please

Look a few posts up I've posted my config

**Comment by jouster1974** [comment]
to report, I upgraded to 2022.10.1 this morning and everything seems to be working fine...including Browser mod...popup on all devices ONLY shows the required popup and no longer the moe info box as well...will monitor going forward but now seems all good

**Comment by e2m32** [comment]
> to report, I upgraded to 2022.10.1 this morning and everything seems to be working fine...including Browser mod...popup on all devices ONLY shows the required popup and no longer the moe info box as well...will monitor going forward but now seems all good

@jouster1974 you gave me hope... I just upgraded to browser_mod 2.1.3 and migrated over my popup cards to the new way of doing things. The cards are defined correctly now in the same view as the entities that I want to override the `more-info` dialog boxes. I was still on HA 2022.9.x... just upgraded to 2022.10.1 and they are still not working... 😢I refreshed, cleared cache though the dev mode on Chrome, and cleared all site data... still no luck.

**Comment by tigers75** [comment]
I don't think it's the same issue, you should check your config and maybe open another issue. 
Meanwhile, can we close this one as resolved?

**Comment by e2m32** [comment]
> I don't think it's the same issue, you should check your config and maybe open another issue. Meanwhile, can we close this one as resolved?

I created a new install of HA for testing and installed everything from scratch. Looks like this feature is working (at least in 2022.10.2). It's not working in combination of the [`custom:mini-climate` card](https://github.com/artem-sedykh/mini-climate-card). That card must call the "more-info" dialog box differently 😢It probably was working the same on my main system, I only tested it in combination with the `custom:mini-climate` card. If anyone else happens to be using this custom card and knows how to fix, that would be amazing. 

@tigers75 I'm good with you closing this out.

**Comment by e2m32** [comment]
> If anyone else happens to be using this custom card and knows how to fix, that would be amazing.

In case this helps someone. This works! 
``` yaml
type: custom:mini-climate
entity: climate.test
tap_action:
  action: call-service
  service: browser_mod.more_info
  service_data:
    entity: climate.test

```

**Comment by tigers75** [comment]
I have no problem with the same card and this code for the pop-up card:

```
type: custom:popup-card
entity: light.faretti2
title: Custom popup
dismissable: true
card:
  type: grid
  cards:
    - type: markdown
      content: '*Zona giorno*'
    - entity: climate.soggiorno
      hvac_mode:
        source:
          heat:
            icon: mdi:power-cycle
            name: riscaldamento
            style: '(value, entity) => ({ color: ''orange''})'
          'off':
            icon: mdi:power
            name: 'off'
      indicators:
        humidity:
          icon:
            template: |
              (value) => (value > 60 ? 'mdi:weather-rainy' : 'mdi:water')
          round: 1
          source:
            entity: sensor.cicalino_am2301_humidity
          unit: '%'
      secondary_info:
        icon: mdi:fire
        type: hvac-action
      target_temperature:
        step: 0.5
      temperature:
        round: 1
        unit: °C
      toggle:
        hide: true
      type: custom:mini-climate
  columns: 1
  square: false
```

**Comment by e2m32** [comment]
> I have no problem with the same card and this code for the pop-up card:

I was doing the opposite; not trying to put a `custom:mini-climate` in a popup, but defining a `custom:mini-climate` card in my main UI. When you tap the card, by default the mini-climate `tap-action` is to open the "more-info" dialog of the climate entity. It must be calling it differently than `browser_mod` expects, so it doesn't open the `browser_mod` defined popup-card, it opens the actual "more-info" dialog. But my work-around above works perfectly. `mini-climate`'s `tap-action` works just like a button, so I can use the `browser_mod.more_info` service.

**Comment by e2m32** [comment]
> > If anyone else happens to be using this custom card and knows how to fix, that would be amazing.
> 
> In case this helps someone. This works!
> 
> ```yaml
> type: custom:mini-climate
> entity: climate.test
> tap_action:
>   action: call-service
>   service: browser_mod.more_info
>   service_data:
>     entity: climate.test
> ```

I take back what I said in the implementation working... I just realized that it opens the `more-info` popup on all registered browsers... I attempted to use a `fire-dom-event`, but for whatever reason it doesn't work with the `custom:mini-climate` card. It works with a button card. I wonder if this is related to the `action: more-info` not working. To make this work with `custom:mini-climate`, does this project need to be updated to support the `fire-dom-event`? If so, is there documentation on how to implement this?

```yaml
type: custom:mini-climate
entity: climate.test
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.more_info
    data:
      entity: climate.test
```
