### ISSUE TITLE
After closing popup with camera stream - sound does not stop

### ISSUE THREAD

**Issue by nsleigh** [thomasloven/hass-browser_mod#795]
My Home Assistant version: 2025.1.3

**What I am doing:**
Calling the service more_info to display a camera stream and then close_popup the popup closes but the audio stream just keeps playing until the browser is refreshed. The browser is running on a Fire Tablet HD 10, if I do the same on a Windows browser (Chrome) the audio stops.

This issues seems to have been reported before [476](https://github.com/thomasloven/hass-browser_mod/issues/476) but there wasn't a solution.

**What I expected to happen:**
The audio should stop when the popup closes.

```yaml
# The least amount of code or steps possible to reproduce my error
action: browser_mod.sequence
data:
  sequence:
    - service: browser_mod.more_info
      data:
        entity: camera.drive_high_resolution_channel
        ignore_popup_card: false
        large: false
    - service: browser_mod.delay
      data:
        time: 10000 #Number in miliseconds
    - service: browser_mod.close_popup
  browser_id: firetablet
# Put your code/steps here
```

**By replacing the space in the checkboxes ([ ]) with an X below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by tsaouste** [comment]
Hi,

I also have the same exact problem with Fully Kiosk Browser on my tablet and the same automation yaml. Mod Browser v2.3.3 and HA 2025.2.3

**Comment by nsleigh** [comment]
I wonder if it is an interaction with fully kiosk as it was ok on my desktop. Might try without kiosk when I get time.

**Comment by tsaouste** [comment]
I tried earlier at the same tablet with Firefox. The same problem again...

**Comment by aalwash** [comment]
> I wonder if it is an interaction with fully kiosk as it was ok on my desktop. Might try without kiosk when I get time.

I've checked both in kiosk mode and normal mode.

It happens on both. The strange part is, I see a ```<video id="remote-stream"``` and when I send `browser mode: close popup`, the popup closes
But somehow the sound of the stream stays open, but I can't find any video object in the HTML anymore

**Comment by dcapslock** [comment]
Just a long shot here. Version 2.3.4 fixed an issue where there could be multiple copies of the code running and hence in fact duplicate code ran for popups, with the second run closing the first. So I am wondering if this is related given it is to do with resources of popup. Anyhow if you have not tried, v2.3.4 it is available on my fork. See [v2.3.4 discussion](https://github.com/dcapslock/hass-browser_mod/discussions/17), specifically the section in [v2.3.4 readme](https://github.com/dcapslock/hass-browser_mod/tree/v2.3.4#phoenix-version) on installing this version.

**Comment by nsleigh** [comment]
I have just got a "Shelly wall display x2" (not recommended!) and that does the same with the standard controls and no browser mod control i.e. click a tile button, the camera is displayed and then manually close and the sound stream keeps running.

**Comment by dcapslock** [comment]
@nsleigh so you are saying the issue happens without browser mod?

**Comment by dcapslock** [comment]
@nsleigh OK. If we can work out what is holding the audio to keep playing, perhaps we can mitigate with some javascript code to run on close of popup.

**Comment by nsleigh** [comment]
@dcapslock I have managed to get this to fail on my Chrome desktop browser now (using browser-mod) so that should make it easier to stop the stream - well it would if I knew what to look for! Any ideas?

**Comment by nsleigh** [comment]
I think the issue with the "Shelly wall display x2" might be a red-herring, if you close the stream and leave the sound playing after a few minutes it stops on its own. I think it may be just a performance issue with the device.

**Comment by dcapslock** [comment]
@nsleigh I am replicating now on my latest MacBook Air so looks to be more than a resource issue. What is interesting is that in my test, the sound stops but then comes back.

**Comment by dcapslock** [comment]
Seems to be that the audio stream(s) are somewhat independent from the video. I say plural 'streams' as audio seems to be started/stopped when buffering takes place, and if one of those audio 'starts' is about the same time as close, then it will stay playing. That is why sometimes I am finding the audio stops but then comes back after close. More research to be done.

**Comment by dcapslock** [comment]
Making some progress. There is a difference in a dialog being closed by UI (X or click outside), as that comes through to HA Frontend from material design mwc-dialog. However, browser_mod dismisses the dialog by firing the `hass-more-info` event with empty entity id, which is a valid way to dmismiss HA More Info dialog. As far as I can see, the HA code does the same, but there must be something different with mwc-dialog does cleanup.

If you are using Chrome as web browser, you can easily see the difference by using chrome://webrtc-internals/. When using browser_mod.close_popup, you will see a new WebRTC session which remains connected. When closing with 'X' no new WebRTC session is made and the existing is closed and removed quite readily.

**Comment by dcapslock** [comment]
OK. Pretty sure I have a valid workaround for this, and perhaps will use this way as a permanent fix in Browser Mod code. Rather than using `browser_mod.close_popup`, use `browser_mod.javascript` as per below. I have also included my testing yaml for a button running a browser mod sequence, though the javascipt code is not as readable.

#### Javascript Code
```
moreInfoDialog=document.querySelector('home-assistant').shadowRoot.querySelector('ha-more-info-dialog');
if (moreInfoDialog) { 
  dialog = moreInfoDialog.shadowRoot.querySelector('ha-dialog'); 
  if (dialog) dialog.close(); 
}
```

#### Yaml example
```
show_name: true
show_icon: true
type: button
name: Test
icon: mdi:check
icon_height: 50px
entity: camera.treecam_1_high
tap_action:
  action: fire-dom-event
  browser_mod:
    service: browser_mod.sequence
    data:
      sequence:
        - service: browser_mod.more_info
          data:
            entity: camera.treecam_1_high
            ignore_popup_card: false
            large: false
        - service: browser_mod.delay
          data:
            time: 15000
        - service: browser_mod.javascript
          data:
            code: >
              moreInfoDialog=document.querySelector('home-assistant').shadowRoot.querySelector('ha-more-info-dialog');
              if (moreInfoDialog) { dialog =
              moreInfoDialog.shadowRoot.querySelector('ha-dialog'); if (dialog)
              dialog.close(); }
```

**Comment by nsleigh** [comment]
First off, thank you for looking at this.

That worked for me (initially it didn't as I copied the code from an email notification and the let's were missing, so these are required on both Windows and an Android tablet.

I too was hearing the audio stop and then restart on closing the dialog.

F.Y.I. I have also moved over to the Phoenix branch if there are any updates to the code.

**Comment by dcapslock** [comment]
Thanks for the feedback. I will look to change closing popups to call close of the dialog directly. Hopefully to be available in the next 2.3.5 beta. 

Not sure about the change in being able to use device id and browser id. The latest 2.3.5 beta fixed being able to use device_id and area_id in a browser_mod call - they are not documented but are avaiable for all calls but needed to be a list. Now they can be both single and list. I had to address this to allow area_id to be used for the new browser_mod.deregister_browser.

**Comment by dcapslock** [comment]
@nsleigh v2.3.5-beta.4 released for testing. This includes updating close_popup to favour closing ha-dialog directly as per this discussion. You can read more about this beta in the [discussion](https://github.com/dcapslock/hass-browser_mod/discussions/21) on my fork. As you are on teh Phoenix fork, you can use the _Redownload_ feature of HACS and select the v2.3.5-beta.4 which is listed as a pre-release. It would be great if you can test both the fix and that all looks well with this beta. Thanks.

**Comment by tsaouste** [comment]
I finally remember to move at phoenix fork. Works like a charm now

**Comment by dcapslock** [comment]
FYI I am working with Thomas on PR for 2.3.8 being released in the mainb repo.

**Comment by dcapslock** [comment]
Fixed in v2.3.8

**Comment by dcapslock** [comment]
FYI. This issue crept back in with dialog refactor in 2.5.0 when the workaround code was removed. [v2.6.4-beta.4](https://github.com/thomasloven/hass-browser_mod/releases/tag/2.6.4-beta.4) adds a `close` parameter to `browser_mod.more_info` which specifically closes the stanard more_info dialog directly with closeDialog() on the element which works whereas using empty entity causes issues due to the way more-info deals with empty entity (it 'loads' and then unloads which confuses the camera stream component as a 'load' of an open dialog always causes a disconnect and reconnect to the DOM to make sure it is topmost).

**Comment by cdmlb** [comment]
Now that Browser mod has switched to using WA.
This problem is back in version 2.8.0+ it seems.
Just before the big update.
I did not have this problem.
Or am I crazy?

**Comment by dcapslock** [comment]
My testing shows that closing more-info using `browser_mod.more_info` with `close: true` still is a viable workaround as was introduced in 2.6.4. Closing with blank entity will exhibit the underlying Frontend issue with closing more-info with blank entity.

**Comment by tanishqmanuja** [comment]
I am new to browser mod and using a popup to display doorbell stream but it keeps playing even after autoclose timeout closes the popup ( i can also see media.enc eating cpu when i run `top` command on adb shell ) - what workaround should work ?

**Comment by dcapslock** [comment]
@tanishqmanuja please create a new issue so you can provide all information required for review.

**Comment by tanishqmanuja** [comment]
Sure, will do with my popup yaml and android logs 
EDIT: Done https://github.com/thomasloven/hass-browser_mod/issues/1215

**Comment by dcapslock** [comment]
@cdmlb 2.9.1-beta.1 could make a difference for you.
